[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "posts"
weight = 10

[[main]]
pre = "github"
url = "https://github.com/prenaissance/blog"
identifier = "github"
weight = 20

[[footer]]
none = "none"
